apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-hw03
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-hw03
  maxReplicas: 6
  minReplicas: 3
  metrics: 
    - type: Resource
      resource:
        name: memory 
        target:
          type: Utilization
          averageUtilization: 50